// Fetch the Goethe-Institut Wortlisten (A1, A2, B1) from the community
// mirror at github.com/ilkermeliksitki/goethe-institute-wordlist and emit
// a SQL seed file ready to apply to D1.
//
// Run:
//   npx tsx scripts/seed/goethe.ts
// Output:
//   migrations/0004_seed_goethe.sql   (commit this; apply with wrangler)

import { writeFileSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'

const REPO = 'ilkermeliksitki/goethe-institute-wordlist'
const RAW = `https://raw.githubusercontent.com/${REPO}/master`
const LEVELS = ['a1', 'a2', 'b1'] as const
type Level = typeof LEVELS[number]

const LETTERS = 'abcdefghijklmnopqrstuvwxyz'.split('')
const HEADER_TOKENS = new Set(['german word', 'wort', 'lemma'])

interface Row {
  display: string
  sentence_de: string
  sentence_en: string
}

interface VocabItem extends Row {
  cefr_level: Level
  lemma: string
  article: string | null
  pos: string | null
}

async function fetchTsv(level: Level, letter: string): Promise<string | null> {
  const url = `${RAW}/${level}/${letter}.tsv`
  const res = await fetch(url)
  if (res.status === 404) return null
  if (!res.ok) throw new Error(`${url} → ${res.status}`)
  return res.text()
}

function parseRows(tsv: string): Row[] {
  const out: Row[] = []
  for (const line of tsv.split(/\r?\n/)) {
    if (!line.trim()) continue
    const cols = line.split('\t')
    if (cols.length < 3) continue
    const [display, sentence_de, sentence_en] = cols
    if (HEADER_TOKENS.has(display.trim().toLowerCase())) continue
    out.push({
      display: display.trim(),
      sentence_de: sentence_de.trim(),
      sentence_en: sentence_en.trim(),
    })
  }
  return out
}

function normalize(display: string): { lemma: string; article: string | null; pos: string | null } {
  let s = display
  let article: string | null = null
  let pos: string | null = null

  // Leading article → noun
  const articleMatch = s.match(/^(der|die|das)\s+(.+)$/i)
  if (articleMatch) {
    article = articleMatch[1].toLowerCase()
    s = articleMatch[2]
    pos = 'noun'
  }

  // Strip plural suffix marker like ",-en" or ",-er" or ",-(e)n"
  s = s.replace(/,\s*-?\(?e?\)?[a-zäöüß]*\s*$/i, '')

  // Strip sense numbers like "(1)", "(2)"
  s = s.replace(/\s*\(\d+\)\s*$/, '')

  return { lemma: s.trim(), article, pos }
}

function sqlString(s: string): string {
  return `'${s.replace(/'/g, "''")}'`
}

async function main() {
  const items: VocabItem[] = []
  for (const level of LEVELS) {
    for (const letter of LETTERS) {
      const tsv = await fetchTsv(level, letter)
      if (!tsv) continue
      const rows = parseRows(tsv)
      for (const row of rows) {
        const { lemma, article, pos } = normalize(row.display)
        if (!lemma) continue
        items.push({ ...row, lemma, article, pos, cefr_level: level })
      }
      process.stderr.write(`  ${level}/${letter}: ${rows.length} rows\n`)
    }
  }
  process.stderr.write(`total parsed: ${items.length} items\n`)

  // Build SQL — chunk multi-row INSERTs to keep statements small.
  // D1 enforces a per-statement size cap (SQLITE_TOOBIG). 25 rows × ~200 char
  // per row × 8 columns stays well under the limit.
  const CHUNK = 25
  const lines: string[] = []
  lines.push('-- Auto-generated by scripts/seed/goethe.ts — DO NOT EDIT BY HAND')
  lines.push('-- Source: github.com/ilkermeliksitki/goethe-institute-wordlist (mirror of Goethe-Institut Wortlisten)')
  lines.push('-- License: word lists are factual data; example sentences are quoted from the same source.')
  lines.push('')

  // 1) vocab_items
  for (let i = 0; i < items.length; i += CHUNK) {
    const slice = items.slice(i, i + CHUNK)
    const values = slice
      .map((it) =>
        `('deu', ${sqlString(it.lemma)}, ${sqlString(it.display)}, ${
          it.article ? sqlString(it.article) : 'NULL'
        }, ${it.pos ? sqlString(it.pos) : 'NULL'}, ${sqlString(it.cefr_level.toUpperCase())}, 'goethe', strftime('%s','now'))`,
      )
      .join(',\n  ')
    lines.push(
      `INSERT OR IGNORE INTO vocab_items (language, lemma, display, article, pos, cefr_level, source, created_at) VALUES`,
    )
    lines.push(`  ${values};`)
    lines.push('')
  }

  // 2) vocab_examples — looked up by the (language, lemma, cefr_level, source) UNIQUE
  for (let i = 0; i < items.length; i += CHUNK) {
    const slice = items.slice(i, i + CHUNK)
    for (const it of slice) {
      lines.push(
        `INSERT INTO vocab_examples (vocab_item_id, sentence_de, sentence_en, source) ` +
          `SELECT id, ${sqlString(it.sentence_de)}, ${sqlString(it.sentence_en)}, 'goethe' ` +
          `FROM vocab_items WHERE language = 'deu' AND lemma = ${sqlString(it.lemma)} ` +
          `AND cefr_level = ${sqlString(it.cefr_level.toUpperCase())} AND source = 'goethe';`,
      )
    }
    lines.push('')
  }


  const outDir = join(process.cwd(), 'migrations')
  mkdirSync(outDir, { recursive: true })
  const outPath = join(outDir, '0004_seed_goethe.sql')
  writeFileSync(outPath, lines.join('\n'))
  process.stderr.write(`wrote ${outPath} (${(lines.join('\n').length / 1024).toFixed(1)} KB)\n`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
