// Ingest Tatoeba DE-EN sentence pairs into D1 via chunked SQL files.
//
// Prerequisites:
//   data/tatoeba/sentences.csv  (extracted from sentences.tar.bz2)
//   data/tatoeba/links.csv      (extracted from links.tar.bz2)
//
// Run:
//   npx tsx scripts/seed/tatoeba.ts
//
// Output:
//   migrations/0005_seed_tatoeba_NNN.sql  (multiple files, chunked to stay
//   under D1's per-migration limits)
//
// Then apply:
//   npx wrangler d1 migrations apply iris --remote

import { createReadStream, writeFileSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'
import { createInterface } from 'node:readline'

const DATA_DIR = join(process.cwd(), 'data', 'tatoeba')
const OUT_DIR = join(process.cwd(), 'migrations')
const CHUNK_ROWS = 50
const MAX_STATEMENTS_PER_FILE = 2000

function sqlString(s: string): string {
  return `'${s.replace(/'/g, "''")}'`
}

async function main() {
  mkdirSync(OUT_DIR, { recursive: true })

  // 1) Read sentences.csv, index DE and EN rows by id
  process.stderr.write('Pass 1: reading sentences.csv (DE + EN only)…\n')
  const deSentences = new Map<string, string>()
  const enSentences = new Map<string, string>()

  const sentRL = createInterface({
    input: createReadStream(join(DATA_DIR, 'sentences.csv')),
    crlfDelay: Infinity,
  })
  let sentTotal = 0
  for await (const line of sentRL) {
    const tab1 = line.indexOf('\t')
    if (tab1 === -1) continue
    const tab2 = line.indexOf('\t', tab1 + 1)
    if (tab2 === -1) continue
    const id = line.slice(0, tab1)
    const lang = line.slice(tab1 + 1, tab2)
    const text = line.slice(tab2 + 1)
    if (lang === 'deu') deSentences.set(id, text)
    else if (lang === 'eng') enSentences.set(id, text)
    sentTotal++
    if (sentTotal % 2_000_000 === 0)
      process.stderr.write(`  …${(sentTotal / 1_000_000).toFixed(0)}M lines scanned\n`)
  }
  process.stderr.write(
    `  DE: ${deSentences.size} sentences, EN: ${enSentences.size} sentences\n`,
  )

  // 2) Read links.csv, collect DE→EN pairs
  process.stderr.write('Pass 2: reading links.csv (DE↔EN pairs)…\n')
  interface Pair {
    deId: string
    deText: string
    enId: string
    enText: string
  }
  const pairs: Pair[] = []
  const seen = new Set<string>()

  const linkRL = createInterface({
    input: createReadStream(join(DATA_DIR, 'links.csv')),
    crlfDelay: Infinity,
  })
  let linkTotal = 0
  for await (const line of linkRL) {
    const tab = line.indexOf('\t')
    if (tab === -1) continue
    const idA = line.slice(0, tab)
    const idB = line.slice(tab + 1)

    let deId: string | undefined, enId: string | undefined
    if (deSentences.has(idA) && enSentences.has(idB)) {
      deId = idA
      enId = idB
    } else if (deSentences.has(idB) && enSentences.has(idA)) {
      deId = idB
      enId = idA
    }
    if (!deId || !enId) continue

    const key = `${deId}:${enId}`
    if (seen.has(key)) continue
    seen.add(key)

    pairs.push({
      deId,
      deText: deSentences.get(deId)!,
      enId,
      enText: enSentences.get(enId)!,
    })

    linkTotal++
    if (linkTotal % 100_000 === 0)
      process.stderr.write(`  …${linkTotal} pairs collected\n`)
  }
  process.stderr.write(`  total DE-EN pairs: ${pairs.length}\n`)

  // 3) Emit SQL files — sentences + sentence_pairs, chunked
  process.stderr.write('Pass 3: emitting SQL migrations…\n')

  let fileIndex = 0
  let stmtCount = 0
  let lines: string[] = []

  const flushFile = () => {
    if (lines.length === 0) return
    const name = `0005_seed_tatoeba_${String(fileIndex).padStart(3, '0')}.sql`
    const path = join(OUT_DIR, name)
    writeFileSync(path, lines.join('\n'))
    process.stderr.write(`  wrote ${name} (${stmtCount} stmts, ${(lines.join('\n').length / 1024).toFixed(0)} KB)\n`)
    fileIndex++
    stmtCount = 0
    lines = []
  }

  const pushStmt = (sql: string) => {
    lines.push(sql)
    stmtCount++
    if (stmtCount >= MAX_STATEMENTS_PER_FILE) flushFile()
  }

  lines.push('-- Auto-generated by scripts/seed/tatoeba.ts — DO NOT EDIT BY HAND')
  lines.push('-- Source: tatoeba.org (CC-BY 2.0 FR)')
  lines.push('')

  // Insert DE sentences in chunks
  for (let i = 0; i < pairs.length; i += CHUNK_ROWS) {
    const slice = pairs.slice(i, i + CHUNK_ROWS)
    const values = slice
      .map(
        (p) =>
          `('tatoeba', ${sqlString(p.deId)}, 'deu', ${sqlString(p.deText)}, 'CC-BY 2.0 FR tatoeba.org')`,
      )
      .join(',\n  ')
    pushStmt(
      `INSERT OR IGNORE INTO sentences (source, source_id, language, text, attribution) VALUES\n  ${values};`,
    )
  }

  // Insert EN sentences in chunks
  for (let i = 0; i < pairs.length; i += CHUNK_ROWS) {
    const slice = pairs.slice(i, i + CHUNK_ROWS)
    const values = slice
      .map(
        (p) =>
          `('tatoeba', ${sqlString(p.enId)}, 'eng', ${sqlString(p.enText)}, 'CC-BY 2.0 FR tatoeba.org')`,
      )
      .join(',\n  ')
    pushStmt(
      `INSERT OR IGNORE INTO sentences (source, source_id, language, text, attribution) VALUES\n  ${values};`,
    )
  }

  // Insert sentence_pairs via subquery lookup
  for (const p of pairs) {
    pushStmt(
      `INSERT OR IGNORE INTO sentence_pairs (sentence_a_id, sentence_b_id) ` +
        `SELECT a.id, b.id FROM sentences a, sentences b ` +
        `WHERE a.source = 'tatoeba' AND a.source_id = ${sqlString(p.deId)} AND a.language = 'deu' ` +
        `AND b.source = 'tatoeba' AND b.source_id = ${sqlString(p.enId)} AND b.language = 'eng';`,
    )
  }

  flushFile()

  process.stderr.write(
    `\nDone. ${fileIndex} migration file(s) generated.\n` +
      `Total pairs: ${pairs.length}\n` +
      `Apply with: npx wrangler d1 migrations apply iris --remote\n`,
  )
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
